## Strategic Marketing for Personal Loans using Python and SQL.

In this project, Thera Bank aims to enhance its marketing strategies by implementing data-driven customer segmentation techniques. By analyzing demographic, financial, and behavioral data, the bank plans to identify customer groups with a higher likelihood of converting from liability customers to personal loan customers. Using digital channels and personalized messages, the goal is to boost campaign success, trim costs, and strengthen customer retention, leading to increased revenue growth.

### Load raw dataset using pandas

In [33]:
import pandas as pd

#--- Read in dataset ---
df = pd.read_csv('./Bank_Personal_Loan_Modelling.csv')
df

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

### Check for Duplicate records
To identify and eliminate duplicates within the dataset.

In [34]:
duplicates = df.duplicated().sum()
duplicates

0

As we can see from above output that we don't have any duplicated records.

### Check missing or Null values

In [35]:
null_values = df.isnull().sum()
null_values

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

As we can see from above output that we don't have any Null records.

### Drop non-essential columns

In [36]:
df.drop(['ID','ZIP Code'],axis=1, inplace= True)
df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

### Filter Negative Experience.
We saw some negative experience in the data, so let's filter those out of the data.

In [37]:
df = df[df['Experience']>=0]
df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

### Transforming Education Levels.
We're transforming the 'Education' data into more comprehensible categories. By mapping the values to 'Undergraduate,' 'Graduate,' and 'Professional,' we simplify the dataset for easier interpretation.

In [38]:
def edu(x):
    if x['Education']==1:
        return "Undergraduate"
    elif x['Education']==2:
        return "Graduate"
    else:
        return "Professional"

# map education to categories
df['EDU']= df.apply(edu, axis=1)
df

/var/folders/9_/qcdxkrws58g7lt3qt26p3_lh0000gn/T/ipykernel_5986/1503565464.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EDU']= df.apply(edu, axis=1)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,EDU
0,25,1,49,4,1.6,1,0,0,1,0,0,0,Undergraduate
1,45,19,34,3,1.5,1,0,0,1,0,0,0,Undergraduate
2,39,15,11,1,1.0,1,0,0,0,0,0,0,Undergraduate
3,35,9,100,1,2.7,2,0,0,0,0,0,0,Graduate
4,35,8,45,4,1.0,2,0,0,0,0,0,1,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0,Professional
4996,30,4,15,4,0.4,1,85,0,0,0,1,0,Undergraduate
4997,63,39,24,2,0.3,3,0,0,0,0,0,0,Professional
4998,65,40,49,3,0.5,2,0,0,0,0,1,0,Graduate
4999,28,4,83,3,0.8,1,0,0,0,0,1,1,Undergraduate

### Categorizing Account Holders.
Let's categorize account holders based on their financial choices. By defining categories like "Holds Securities & Deposits," "Does not hold Securities & Deposits account," "Holds only Securities account," and "Holds only Deposits account," we provide a clear insight into customers' financial preferences. This task streamlines data interpretation, offering valuable insights for strategic decision-making.

In [39]:
def security(y):
    if(y['Securities Account'] == 1) & (y['CD Account'] == 1):
        return "Holds Securities & Deposits"
    if(y['Securities Account'] == 0) & (y['CD Account'] == 0):
        return "Does not hold Securities & Deposits account"
    if(y['Securities Account'] == 1) & (y['CD Account'] == 0):
        return "Holds only Securities account"
    if(y['Securities Account'] == 0) & (y['CD Account'] == 1):
        return "Holds only Deposits account"

df['Account_holder_category'] = df.apply(security, axis=1)
df

/var/folders/9_/qcdxkrws58g7lt3qt26p3_lh0000gn/T/ipykernel_5986/1030109163.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Account_holder_category'] = df.apply(security, axis=1)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,EDU,Account_holder_category
0,25,1,49,4,1.6,1,0,0,1,0,0,0,Undergraduate,Holds only Securities account
1,45,19,34,3,1.5,1,0,0,1,0,0,0,Undergraduate,Holds only Securities account
2,39,15,11,1,1.0,1,0,0,0,0,0,0,Undergraduate,Does not hold Securities & Deposits account
3,35,9,100,1,2.7,2,0,0,0,0,0,0,Graduate,Does not hold Securities & Deposits account
4,35,8,45,4,1.0,2,0,0,0,0,0,1,Graduate,Does not hold Securities & Deposits account
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0,Professional,Does not hold Securities & Deposits account
4996,30,4,15,4,0.4,1,85,0,0,0,1,0,Undergraduate,Does not hold Securities & Deposits account
4997,63,39,24,2,0.3,3,0,0,0,0,0,0,Professional,Does not hold Securities & Deposits account
4998,65,40,49,3,0.5,2,0,0,0,0,1,0,Graduate,Does not hold Securities & Deposits account
4999,28,4,83,3,0.8,1,0,0,0,0,1,1,Undergraduate,Does not hold Securities & Deposits account

### Save the dataset for further analysis.

In [40]:
#export the cleaned data
df.to_csv('liability.csv',index= False)

## Let's explore the cleaned dataset using MySQL

### Total Count from cleaned dataset

In [10]:
%%sql
Select count(*)
from liability

 * mysql+pymysql://bad584af:***@localhost/bad584af
1 rows affected.

[(4948,)]

### Checking Average Income of Customers in dollars ($)

In [11]:
%%sql
Select avg(income) as AverageIncome
from liability

 * mysql+pymysql://bad584af:***@localhost/bad584af
1 rows affected.

[(Decimal('73.8145'),)]

### Identifying High-Potential Customers (top 10) based on Income.

These customers represent a prime target for personalized marketing and personal loan conversion efforts. The insights gained from this analysis are instrumental in optimizing campaigns to attract and retain these high-value customers, ultimately driving revenue growth and banking success.

In [12]:
%%sql
Select *
from liability
order by income desc
limit 10

 * mysql+pymysql://bad584af:***@localhost/bad584af
10 rows affected.

[(48, 24, 224, 2, 6.67, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (45, 21, 218, 2, 6.67, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (26, 2, 205, 1, 6.33, 1, 271, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (46, 21, 205, 2, 8.8, 1, 181, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (30, 4, 204, 2, 4.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 18, 204, 2, 8.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (46, 21, 204, 2, 2.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (35, 5, 203, 1, 10.0, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (47, 22, 203, 2, 8.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (59, 35, 202, 1, 4.7, 1, 553, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account')]

### Calculate average income within different Education levels

In [44]:
# better to use EDU instead of Education

In [13]:
%%sql
Select Education, avg(income) as AverageIncome
from liability
group by Education

 * mysql+pymysql://bad584af:***@localhost/bad584af
3 rows affected.

[(1, Decimal('85.5923')), (2, Decimal('64.4535')), (3, Decimal('66.0398'))]

### Top Income Earners by Education.

In [14]:
%%sql
With RankedData as(
Select *, RANK() OVER (PARTITION BY Education ORDER BY Income Desc) as IncomeRank
from liability)

Select *
from RankedData
where IncomeRank<=2

 * mysql+pymysql://bad584af:***@localhost/bad584af
6 rows affected.

[(48, 24, 224, 2, 6.67, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account', 1),
 (45, 21, 218, 2, 6.67, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account', 2),
 (43, 16, 201, 1, 10.0, 2, 0, 1, 0, 0, 0, 1, 'Graduate', 'Does not hold Securities & Deposits account', 1),
 (54, 27, 195, 2, 4.75, 2, 477, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account', 2),
 (35, 5, 203, 1, 10.0, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account', 1),
 (45, 15, 202, 3, 10.0, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account', 2)]

### Profiling Customer Demographics.

This task is pivotal as it offers a granular view of the customer base, helping to craft personalized marketing strategies and pinpoint specific segments for personal loan conversion efforts. By understanding the unique characteristics of each age group, the bank can tailor its approach, ensuring that every customer, whether aged 18-30, 31-45, 46-60, or 61+, receives targeted and effective messaging. This data-driven approach promises to enhance customer engagement and drive revenue growth.

In [22]:
%%sql

Select 
CASE when Age between 18 and 30 then '18-30'
when Age between 31 and 45 then '31-45'
when Age between 46 and 60 then '46-60'
ELSE '61+'
END as agegroup, count(*)
from liability
group by agegroup

 * mysql+pymysql://bad584af:***@localhost/bad584af
4 rows affected.

[('18-30', 572), ('31-45', 1895), ('46-60', 1934), ('61+', 547)]

### Analyzing Age vs. Credit Card Spending.

This task is essential as it helps us identify and understand customers who are above-average spenders. The insights garnered here provide a deeper understanding of the demographics of these high-CCAvg individuals.

In [27]:
%%sql

Select avg(Age)
from liability
where CCAvg> (Select avg(CCAvg) 
      From liability)

 * mysql+pymysql://bad584af:***@localhost/bad584af
1 rows affected.

[(Decimal('44.8300'),)]

### Unveiling High-Income Elite.

We extract customer records with incomes exceeding 1.5 times the average income. This task is crucial as it identifies the financially well-endowed individuals within our customer base. These high-income customers present a prime opportunity for personal loan conversion, as their financial capacity opens doors for higher-value financial products.

In [29]:
%%sql

Select*
from liability
where Income > (Select avg(Income) from liability) *1.5

 * mysql+pymysql://bad584af:***@localhost/bad584af
1051 rows affected.

[(34, 9, 180, 1, 8.9, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (48, 23, 114, 2, 3.8, 3, 0, 0, 1, 0, 0, 0, 'Professional', 'Holds only Securities account'),
 (67, 41, 112, 1, 2.0, 1, 0, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (38, 14, 130, 4, 4.7, 3, 134, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (46, 21, 193, 2, 8.1, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (36, 11, 152, 2, 3.9, 1, 159, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (46, 20, 158, 1, 2.4, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (38, 13, 119, 1, 3.3, 2, 0, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (59, 35, 121, 1, 2.9, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 18, 141, 3, 5.0, 3, 0, 1, 1, 1, 1, 0, 'Professional', 'Holds Securities & Deposits'),
 (32, 7, 132, 4, 1.1, 2, 412, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (37, 12, 194, 4, 0.2, 3, 211, 1, 1, 1, 1, 1, 'Professional', 'Holds Securities & Deposits'),
 (61, 37, 131, 1, 2.9, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 26, 190, 3, 2.1, 3, 240, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (41, 17, 139, 2, 8.0, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 31, 131, 2, 1.2, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (31, 5, 188, 2, 4.5, 1, 455, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (47, 21, 125, 1, 5.7, 1, 112, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (59, 35, 131, 1, 3.8, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 18, 115, 1, 3.5, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 130, 1, 5.0, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (28, 3, 135, 2, 3.3, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (31, 7, 135, 4, 3.8, 2, 0, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (54, 30, 133, 2, 2.6, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (55, 30, 118, 4, 5.6, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (65, 39, 121, 1, 2.0, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (54, 28, 161, 1, 2.9, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (32, 7, 112, 1, 4.6, 1, 366, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (31, 5, 115, 2, 1.3, 1, 101, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 34, 149, 4, 7.2, 2, 0, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (49, 25, 128, 2, 0.4, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (59, 35, 124, 1, 7.4, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 163, 2, 0.4, 1, 116, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (46, 22, 118, 2, 7.5, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (26, 0, 132, 3, 6.5, 3, 0, 1, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (29, 0, 134, 4, 6.5, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (27, 1, 112, 4, 2.1, 3, 0, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (27, 1, 138, 2, 2.0, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (38, 13, 171, 2, 7.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 17, 168, 2, 7.9, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (24, 0, 135, 1, 1.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (29, 3, 148, 3, 4.1, 1, 0, 1, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (39, 14, 115, 1, 1.0, 3, 0, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (46, 21, 159, 3, 1.9, 3, 315, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (64, 40, 169, 2, 2.1, 1, 122, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (55, 29, 112, 2, 1.4, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (53, 29, 144, 2, 6.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (48, 24, 165, 1, 5.0, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (36, 11, 158, 1, 5.1, 3, 0, 1, 0, 1, 1, 1, 'Professional', 'Holds only Deposits account'),
 (64, 39, 172, 4, 3.1, 1, 282, 1, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (57, 33, 155, 1, 7.4, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (27, 3, 125, 2, 0.6, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (47, 23, 148, 2, 7.5, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (65, 39, 170, 3, 7.9, 3, 99, 1, 0, 1, 1, 0, 'Professional', 'Holds only Deposits account'),
 (53, 29, 120, 4, 2.7, 2, 111, 1, 1, 1, 1, 0, 'Graduate', 'Holds Securities & Deposits'),
 (54, 28, 170, 2, 6.2, 2, 325, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (47, 21, 138, 1, 0.0, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (65, 41, 134, 3, 3.9, 3, 121, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (42, 16, 111, 2, 1.2, 3, 251, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (64, 39, 129, 1, 2.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (39, 14, 155, 2, 3.9, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 19, 172, 2, 4.3, 3, 391, 1, 1, 1, 1, 0, 'Professional', 'Holds Securities & Deposits'),
 (34, 9, 122, 1, 0.0, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 15, 159, 1, 5.5, 3, 0, 1, 0, 1, 1, 0, 'Professional', 'Holds only Deposits account'),
 (65, 39, 150, 2, 6.9, 1, 196, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 21, 152, 2, 7.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (49, 25, 195, 4, 3.0, 1, 617, 1, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (32, 8, 128, 2, 4.33, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (52, 26, 121, 1, 7.3, 1, 167, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (57, 31, 165, 1, 1.6, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (40, 16, 119, 2, 4.2, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (56, 30, 158, 4, 6.1, 1, 0, 1, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 32, 114, 2, 2.0, 1, 402, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (28, 4, 191, 1, 6.33, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (63, 38, 140, 1, 2.5, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 32, 122, 2, 0.3, 1, 360, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (29, 3, 153, 2, 2.0, 1, 392, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 118, 2, 3.3, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (40, 15, 173, 4, 6.6, 1, 0, 1, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (39, 14, 113, 1, 1.0, 3, 0, 0, 1, 0, 1, 0, 'Professional', 'Holds only Securities account'),
 (28, 4, 155, 4, 5.3, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 173, 2, 1.4, 1, 419, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (30, 6, 141, 2, 4.33, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 153, 2, 7.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 32, 113, 2, 1.4, 1, 270, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (57, 32, 174, 1, 6.8, 2, 466, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (65, 41, 133, 4, 2.0, 1, 0, 1, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 20, 155, 1, 7.0, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (36, 10, 179, 3, 6.6, 1, 0, 1, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (36, 11, 133, 1, 3.8, 1, 290, 0, 1, 1, 1, 1, 'Undergraduate', 'Holds Securities & Deposits'),
 (45, 19, 125, 1, 2.4, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (28, 3, 115, 4, 3.1, 2, 0, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (46, 20, 145, 2, 6.3, 1, 0, 0, 1, 1, 1, 0, 'Undergraduate', 'Holds Securities & Deposits'),
 (43, 19, 161, 2, 7.5, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 26, 113, 1, 1.3, 3, 161, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (58, 32, 113, 2, 3.8, 2, 119, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (58, 28, 122, 1, 3.0, 3, 115, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (35, 10, 200, 2, 3.0, 1, 458, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (60, 36, 141, 2, 2.1, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (29, 4, 183, 3, 8.3, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (48, 22, 149, 2, 5.5, 2, 0, 1, 1, 1, 1, 0, 'Graduate', 'Holds Securities & Deposits'),
 (64, 39, 182, 1, 1.2, 2, 547, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (60, 34, 114, 2, 6.9, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 152, 3, 6.1, 2, 0, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 150, 2, 3.3, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (60, 36, 132, 2, 6.0, 1, 470, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 32, 173, 1, 4.6, 2, 88, 1, 0, 1, 1, 0, 'Graduate', 'Holds only Deposits account'),
 (25, 1, 113, 2, 0.2, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 24, 173, 1, 1.0, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 17, 160, 2, 8.0, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 118, 2, 6.8, 1, 112, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 16, 113, 1, 1.0, 3, 211, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (26, 2, 205, 1, 6.33, 1, 271, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (64, 39, 122, 4, 0.2, 1, 378, 1, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 25, 132, 1, 0.3, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 131, 1, 4.9, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (30, 6, 141, 2, 4.33, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (35, 10, 164, 2, 7.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (28, 2, 149, 2, 7.2, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (39, 15, 118, 2, 1.9, 1, 0, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (53, 28, 175, 3, 3.6, 3, 0, 1, 0, 1, 1, 1, 'Professional', 'Holds only Deposits account'),
 (49, 25, 161, 3, 6.5, 2, 485, 1, 1, 1, 0, 0, 'Graduate', 'Holds Securities & Deposits'),
 (39, 15, 128, 1, 3.4, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 149, 2, 6.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (40, 16, 114, 1, 3.4, 1, 300, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (31, 7, 128, 1, 6.0, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (48, 22, 152, 1, 3.5, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (56, 30, 141, 2, 0.5, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (29, 5, 135, 2, 0.6, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (28, 3, 170, 1, 0.1, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (65, 40, 129, 1, 1.3, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (37, 12, 180, 1, 8.6, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (63, 37, 139, 2, 6.9, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (33, 8, 115, 4, 2.9, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (41, 17, 114, 2, 1.8, 2, 0, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (57, 32, 165, 4, 2.7, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (40, 16, 120, 2, 6.1, 1, 196, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (35, 10, 139, 2, 7.8, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 21, 152, 2, 1.4, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (47, 22, 122, 1, 5.1, 3, 163, 1, 1, 0, 0, 0, 'Professional', 'Holds only Securities account'),
 (54, 29, 129, 4, 4.2, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (39, 14, 165, 2, 3.3, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (65, 41, 185, 3, 2.0, 2, 0, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (52, 26, 112, 1, 2.4, 1, 0, 0, 1, 1, 1, 1, 'Undergraduate', 'Holds Securities & Deposits'),
 (46, 21, 204, 2, 2.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (34, 9, 164, 1, 6.0, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (43, 17, 164, 1, 2.4, 1, 449, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (32, 7, 112, 1, 3.8, 1, 81, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (29, 4, 115, 1, 1.9, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 17, 141, 2, 7.6, 1, 92, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 32, 129, 1, 7.4, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 34, 148, 1, 4.7, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 21, 132, 3, 1.2, 2, 0, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (39, 15, 119, 2, 6.1, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 20, 114, 2, 4.4, 2, 0, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (43, 18, 140, 1, 7.0, 1, 205, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (61, 35, 152, 3, 3.3, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (64, 37, 138, 2, 2.8, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (52, 27, 195, 1, 8.1, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (45, 20, 154, 2, 2.8, 1, 0, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (29, 5, 138, 2, 4.33, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (26, 2, 172, 2, 6.9, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (54, 28, 165, 1, 4.1, 3, 0, 1, 0, 1, 1, 1, 'Professional', 'Holds only Deposits account'),
 (41, 16, 120, 2, 3.9, 1, 0, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 26, 135, 2, 4.6, 3, 91, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (53, 28, 192, 2, 6.4, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (56, 32, 158, 3, 3.7, 3, 0, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (54, 30, 194, 3, 6.0, 3, 587, 1, 1, 1, 1, 1, 'Professional', 'Holds Securities & Deposits'),
 (44, 20, 160, 2, 7.6, 1, 0, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (46, 22, 164, 2, 7.6, 1, 0, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (45, 15, 202, 3, 10.0, 3, 0, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (31, 7, 173, 1, 6.0, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (55, 29, 132, 3, 5.9, 2, 307, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (52, 27, 162, 1, 8.1, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (54, 29, 111, 1, 0.1, 3, 0, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (50, 25, 130, 1, 1.1, 2, 0, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (51, 25, 145, 1, 0.3, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (36, 12, 150, 4, 5.4, 1, 0, 1, 1, 1, 1, 0, 'Undergraduate', 'Holds Securities & Deposits'),
 (58, 33, 142, 2, 3.9, 1, 193, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (57, 33, 121, 1, 4.3, 1, 0, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (27, 2, 155, 1, 0.8, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (59, 33, 113, 2, 2.0, 1, 77, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (63, 37, 124, 3, 5.0, 2, 170, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (40, 15, 161, 2, 3.3, 1, 0, 0, 1, 0, 0, 1, 'Undergraduate', 'Holds only Securities account'),
 (44, 19, 154, 2, 8.8, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 25, 185, 1, 1.7, 1, 0, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 16, 118, 2, 3.3, 1, 0, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (57, 33, 182, 2, 3.3, 3, 372, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (32, 6, 120, 4, 5.4, 1, 301, 1, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (50, 24, 161, 3, 3.4, 1, 212, 1, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),

### Family Dynamics Analysis.

In [30]:
%%sql

Select min(Age), Family
from liability
group by Family

 * mysql+pymysql://bad584af:***@localhost/bad584af
4 rows affected.

[(24, 4), (24, 3), (24, 1), (25, 2)]

### Mortgage Holders.

We retrieve customer records where the mortgage amount is greater than zero. This task is pivotal as it identifies customers who are indebted through mortgages, offering a specific demographic segment for in-depth analysis such as Debt to Income Ratio (higher the DTI, more likley customer might default)

In [31]:
%%sql

Select *
from liability
where Mortgage >0

 * mysql+pymysql://bad584af:***@localhost/bad584af
1526 rows affected.

[(37, 13, 29, 4, 0.4, 2, 155, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (35, 10, 81, 3, 0.6, 2, 104, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (38, 14, 130, 4, 4.7, 3, 134, 1, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (56, 31, 25, 4, 0.9, 2, 111, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (29, 5, 62, 1, 1.2, 1, 260, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 18, 43, 2, 0.7, 1, 163, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (36, 11, 152, 2, 3.9, 1, 159, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 29, 3, 0.5, 1, 97, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (59, 35, 35, 1, 1.2, 3, 122, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (53, 28, 41, 2, 0.6, 3, 193, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (51, 25, 71, 1, 1.4, 3, 198, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (38, 13, 80, 4, 0.7, 3, 285, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (32, 7, 132, 4, 1.1, 2, 412, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (39, 14, 43, 3, 0.7, 2, 153, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (37, 12, 194, 4, 0.2, 3, 211, 1, 1, 1, 1, 1, 'Professional', 'Holds Securities & Deposits'),
 (30, 6, 72, 1, 0.1, 1, 207, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 26, 190, 3, 2.1, 3, 240, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (31, 5, 188, 2, 4.5, 1, 455, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (47, 21, 125, 1, 5.7, 1, 112, 0, 1, 0, 0, 0, 'Undergraduate', 'Holds only Securities account'),
 (62, 36, 105, 2, 2.8, 1, 336, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (53, 23, 45, 4, 2.0, 3, 132, 0, 1, 0, 0, 0, 'Professional', 'Holds only Securities account'),
 (50, 26, 19, 2, 0.4, 1, 118, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (60, 36, 41, 4, 1.3, 1, 174, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (40, 16, 42, 4, 2.2, 2, 126, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (60, 34, 64, 2, 1.7, 3, 236, 0, 1, 0, 1, 0, 'Professional', 'Holds only Securities account'),
 (53, 23, 44, 3, 1.0, 3, 198, 0, 0, 0, 1, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (56, 32, 38, 4, 1.3, 1, 166, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 18, 43, 1, 0.7, 1, 136, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (33, 7, 32, 1, 0.6, 3, 166, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (40, 15, 82, 3, 1.0, 1, 309, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 34, 92, 2, 2.8, 1, 103, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 33, 61, 2, 2.3, 3, 193, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (32, 7, 112, 1, 4.6, 1, 366, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (39, 15, 78, 4, 2.4, 1, 118, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (31, 5, 115, 2, 1.3, 1, 101, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (34, 8, 82, 1, 2.7, 2, 251, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (28, 4, 81, 3, 1.5, 1, 276, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 25, 31, 2, 0.4, 3, 161, 0, 0, 0, 1, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (35, 11, 58, 3, 2.0, 1, 149, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 25, 83, 4, 3.6, 3, 188, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (52, 28, 163, 2, 0.4, 1, 116, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 25, 44, 3, 1.0, 2, 135, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (29, 3, 65, 4, 1.8, 2, 244, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (51, 27, 38, 2, 1.0, 3, 164, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (36, 12, 10, 4, 0.7, 2, 81, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (46, 21, 159, 3, 1.9, 3, 315, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (64, 40, 169, 2, 2.1, 1, 122, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 25, 29, 1, 0.3, 3, 140, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (34, 10, 13, 4, 1.0, 1, 95, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (55, 31, 9, 4, 0.7, 1, 89, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (27, 3, 59, 4, 0.0, 1, 90, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (56, 31, 61, 2, 1.9, 2, 105, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (38, 12, 91, 4, 1.4, 2, 100, 0, 0, 0, 0, 1, 'Graduate', 'Does not hold Securities & Deposits account'),
 (64, 39, 172, 4, 3.1, 1, 282, 1, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (46, 22, 69, 2, 1.7, 1, 209, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (38, 14, 92, 2, 0.0, 1, 249, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 27, 58, 4, 1.8, 3, 91, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (47, 22, 53, 4, 1.9, 3, 98, 0, 1, 1, 0, 1, 'Professional', 'Holds Securities & Deposits'),
 (48, 24, 71, 2, 1.7, 1, 145, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (46, 19, 38, 3, 2.5, 2, 135, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (26, 1, 80, 1, 0.8, 2, 150, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (51, 26, 70, 1, 1.2, 1, 169, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 16, 75, 1, 3.7, 3, 280, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (65, 39, 170, 3, 7.9, 3, 99, 1, 0, 1, 1, 0, 'Professional', 'Holds only Deposits account'),
 (41, 17, 78, 4, 0.8, 1, 78, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (53, 29, 120, 4, 2.7, 2, 111, 1, 1, 1, 1, 0, 'Graduate', 'Holds Securities & Deposits'),
 (55, 29, 99, 2, 1.4, 1, 264, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (26, 1, 55, 3, 2.6, 3, 113, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (30, 6, 29, 3, 1.0, 2, 117, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (54, 28, 170, 2, 6.2, 2, 325, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (65, 41, 134, 3, 3.9, 3, 121, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (66, 40, 42, 2, 0.7, 3, 138, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (56, 30, 55, 1, 1.4, 1, 77, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 16, 111, 2, 1.2, 3, 251, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (27, 1, 74, 4, 1.8, 2, 112, 0, 0, 0, 1, 1, 'Graduate', 'Does not hold Securities & Deposits account'),
 (49, 23, 23, 4, 0.6, 3, 98, 0, 1, 0, 0, 0, 'Professional', 'Holds only Securities account'),
 (47, 22, 81, 1, 2.9, 1, 138, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (29, 3, 45, 4, 0.2, 1, 158, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (30, 5, 22, 4, 0.5, 3, 109, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (33, 8, 64, 4, 2.1, 3, 164, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (51, 25, 45, 3, 0.6, 2, 131, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (44, 19, 172, 2, 4.3, 3, 391, 1, 1, 1, 1, 0, 'Professional', 'Holds Securities & Deposits'),
 (43, 16, 8, 3, 0.67, 2, 88, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (30, 5, 38, 4, 0.8, 1, 129, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (65, 39, 150, 2, 6.9, 1, 196, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (49, 25, 195, 4, 3.0, 1, 617, 1, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (60, 35, 22, 1, 1.3, 1, 123, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 26, 121, 1, 7.3, 1, 167, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (27, 2, 110, 4, 1.8, 3, 190, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (60, 34, 64, 1, 0.8, 2, 248, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 101, 3, 4.4, 2, 82, 1, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (58, 32, 114, 2, 2.0, 1, 402, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 32, 122, 2, 0.3, 1, 360, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (29, 3, 153, 2, 2.0, 1, 392, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (31, 6, 55, 4, 2.0, 2, 185, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (35, 5, 22, 1, 0.67, 3, 103, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (54, 24, 63, 3, 1.4, 3, 138, 0, 0, 0, 1, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (51, 27, 12, 4, 0.5, 2, 78, 0, 1, 0, 1, 0, 'Graduate', 'Holds only Securities account'),
 (26, 2, 60, 2, 3.0, 1, 132, 1, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 20, 173, 2, 1.4, 1, 419, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 30, 24, 2, 0.4, 3, 88, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (38, 14, 42, 1, 2.0, 2, 81, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (58, 32, 113, 2, 1.4, 1, 270, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (54, 24, 29, 3, 1.0, 3, 148, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (57, 32, 174, 1, 6.8, 2, 466, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (32, 8, 98, 2, 2.0, 2, 175, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (63, 37, 30, 2, 1.0, 3, 159, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (36, 12, 25, 4, 1.0, 1, 147, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 30, 44, 4, 0.7, 2, 174, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (49, 25, 20, 4, 1.0, 1, 111, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (30, 5, 98, 2, 3.1, 1, 220, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (53, 28, 18, 4, 0.1, 3, 109, 0, 1, 1, 1, 1, 'Professional', 'Holds Securities & Deposits'),
 (29, 2, 30, 4, 1.5, 2, 112, 0, 0, 0, 0, 1, 'Graduate', 'Does not hold Securities & Deposits account'),
 (54, 28, 93, 1, 4.9, 1, 133, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (61, 36, 60, 3, 0.5, 2, 182, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (36, 11, 133, 1, 3.8, 1, 290, 0, 1, 1, 1, 1, 'Undergraduate', 'Holds Securities & Deposits'),
 (49, 22, 82, 1, 2.67, 2, 125, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (35, 8, 38, 4, 1.0, 2, 124, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (32, 7, 35, 3, 1.3, 1, 116, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (62, 38, 24, 2, 1.0, 1, 116, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 26, 113, 1, 1.3, 3, 161, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (39, 13, 75, 3, 2.1, 1, 224, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 31, 4, 0.2, 1, 141, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (61, 35, 50, 3, 1.4, 3, 112, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (58, 32, 113, 2, 3.8, 2, 119, 1, 0, 1, 1, 1, 'Graduate', 'Holds only Deposits account'),
 (64, 39, 59, 2, 1.5, 1, 139, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (58, 28, 122, 1, 3.0, 3, 115, 1, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (64, 39, 42, 3, 0.5, 2, 116, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (35, 10, 200, 2, 3.0, 1, 458, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (66, 42, 35, 1, 1.9, 2, 172, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (50, 24, 30, 4, 0.1, 1, 161, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 31, 4, 0.3, 1, 156, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (64, 39, 182, 1, 1.2, 2, 547, 1, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (64, 39, 24, 4, 0.4, 2, 78, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (60, 36, 132, 2, 6.0, 1, 470, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 32, 173, 1, 4.6, 2, 88, 1, 0, 1, 1, 0, 'Graduate', 'Holds only Deposits account'),
 (55, 30, 84, 2, 3.7, 1, 304, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (42, 18, 34, 4, 0.3, 1, 104, 0, 1, 0, 1, 0, 'Undergraduate', 'Holds only Securities account'),
 (31, 5, 39, 4, 1.8, 3, 185, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (52, 28, 118, 2, 6.8, 1, 112, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (51, 26, 62, 1, 1.3, 2, 221, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (39, 14, 54, 3, 3.0, 1, 108, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (41, 16, 113, 1, 1.0, 3, 211, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (54, 27, 43, 3, 1.0, 2, 169, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (34, 9, 48, 1, 2.5, 3, 105, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (61, 37, 54, 4, 1.2, 2, 129, 0, 0, 0, 1, 1, 'Graduate', 'Does not hold Securities & Deposits account'),
 (36, 11, 72, 1, 2.8, 1, 224, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (64, 38, 79, 2, 2.8, 1, 179, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (26, 2, 205, 1, 6.33, 1, 271, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (33, 8, 65, 2, 0.1, 1, 89, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (64, 39, 122, 4, 0.2, 1, 378, 1, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (62, 37, 39, 2, 2.8, 1, 113, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (31, 5, 11, 1, 0.4, 2, 76, 0, 0, 0, 0, 1, 'Graduate', 'Does not hold Securities & Deposits account'),
 (57, 32, 21, 1, 0.3, 3, 117, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (63, 38, 54, 3, 2.4, 1, 90, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 19, 28, 4, 0.3, 1, 87, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (27, 2, 68, 3, 2.6, 3, 203, 0, 1, 0, 0, 0, 'Professional', 'Holds only Securities account'),
 (44, 14, 44, 3, 2.0, 3, 180, 0, 1, 1, 1, 1, 'Professional', 'Holds Securities & Deposits'),
 (28, 3, 52, 4, 2.2, 1, 230, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (34, 8, 35, 4, 0.8, 1, 137, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (60, 34, 21, 3, 0.3, 3, 129, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (49, 25, 24, 4, 0.2, 1, 138, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (33, 7, 32, 1, 0.6, 3, 152, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (34, 9, 41, 2, 0.1, 1, 161, 0, 0, 0, 1, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (40, 14, 70, 3, 2.1, 1, 185, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (49, 25, 161, 3, 6.5, 2, 485, 1, 1, 1, 0, 0, 'Graduate', 'Holds Securities & Deposits'),
 (44, 18, 72, 1, 0.7, 3, 155, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (40, 16, 114, 1, 3.4, 1, 300, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 24, 94, 1, 4.9, 1, 272, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (50, 26, 85, 1, 0.0, 1, 144, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (42, 18, 41, 1, 1.8, 1, 94, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (56, 31, 11, 2, 0.2, 3, 90, 0, 0, 0, 0, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (63, 38, 28, 2, 0.5, 2, 89, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (28, 3, 70, 4, 2.2, 1, 240, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (34, 8, 81, 3, 0.9, 2, 208, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 81, 3, 1.8, 2, 275, 0, 0, 0, 0, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (49, 23, 32, 4, 1.8, 1, 83, 0, 0, 0, 0, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (63, 37, 42, 2, 0.7, 3, 115, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (41, 17, 92, 2, 1.9, 1, 131, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (44, 19, 34, 1, 0.3, 3, 78, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (33, 6, 54, 2, 1.67, 2, 122, 0, 0, 0, 1, 0, 'Graduate', 'Does not hold Securities & Deposits account'),
 (52, 28, 64, 2, 1.0, 3, 211, 0, 0, 0, 1, 0, 'Professional', 'Does not hold Securities & Deposits account'),
 (30, 6, 42, 1, 0.2, 3, 100, 0, 0, 0, 0, 1, 'Professional', 'Does not hold Securities & Deposits account'),
 (45, 19, 71, 4, 2.9, 1, 218, 0, 0, 1, 1, 1, 'Undergraduate', 'Holds only Deposits account'),
 (32, 7, 35, 3, 1.3, 1, 108, 0, 0, 0, 0, 1, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (60, 35, 35, 3, 0.2, 1, 169, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (40, 16, 120, 2, 6.1, 1, 196, 0, 0, 0, 1, 0, 'Undergraduate', 'Does not hold Securities & Deposits account'),
 (43, 18, 85, 1, 3.7, 3, 327, 0, 1, 0, 1, 0, 'Professional', 'Holds only Securities account'),

### Understanding Customer Distribution

In [32]:
%%sql

Select Count(*), Education
from liability
group by Education

 * mysql+pymysql://bad584af:***@localhost/bad584af
3 rows affected.

[(2080, 1), (1387, 2), (1481, 3)]